Add database
AlexeyKirilyuk/java-filmorate pull request #19
Opened 2023-05-08 15:18 UTC by AlexeyKirilyuk

2023-05-09 18:06 UTC, mikita95 requested changes
Все сделано очень хорошо. Нужно еще немного поправить запросы только.

2023-05-09 18:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreTable.java
> +    public List<Genre> getFilmGenresById(int idFilm) {
Эту операцию можно выполнить используя один запрос (нужно использовать join) - сейчас реализация неэффективная. Запрос в базе данных - довольно дорогая вещь. Это хождение по сети, выполнения запросов, передача данных, блокировки данных и т.д.

2023-05-09 18:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersTable.java
> +    private Integer getMaxIdUser() {
Этот запрос сейчас не нужен

2023-05-10 14:51 UTC, AlexeyKirilyuk commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS Genre (
Исправил

2023-05-10 14:51 UTC, AlexeyKirilyuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreTable.java
> +    public List<Genre> getFilmGenresById(int idFilm) {
Исправил

2023-05-10 14:51 UTC, AlexeyKirilyuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreTable.java
> +    public List<Genre> getFilmGenres() {
Исправил

2023-05-10 14:51 UTC, AlexeyKirilyuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmTable.java
> +    public Integer getMaxIdFilm() {
Исправил

2023-05-10 14:51 UTC, AlexeyKirilyuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersTable.java
> +    private Integer getMaxIdUser() {
Исправил

2023-05-10 19:56 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-05-11 08:38 UTC, merged